[build]
  command = "npm install && npm run build"
  publish = "dist"
  base = "/"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  NODE_ENV = "production"

[build.processing]
  skip_processing = true

[build.processing.css]
  bundle = true
  minify = true 